# Generated by Django 2.1.4 on 2019-03-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('userid', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=250)),
                ('user_last_name', models.CharField(max_length=250)),
                ('user_email', models.CharField(max_length=250)),
                ('user_password', models.CharField(max_length=250)),
            ],
        ),
    ]
